"use client";
import { useEffect, useMemo, useState } from "react";
import ProtectedRoute from "@/components/ProtectedRoute";
import Navbar from "@/components/Navbar";
import API from "@/lib/api";
import { Box, Button, Pagination, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import DownloadIcon from "@mui/icons-material/Download";
import DeleteIcon from "@mui/icons-material/Delete";
const headings = ["Name", "Email", "Mobile", "Insurance", "Message", "Status", "Uploaded", "Actions"];
const csvValue = (value) => `"${String(value ?? "").replaceAll('"', '""')}"`;
export default function ContactsPage() {
  const [leads, setLeads] = useState([]); const [search, setSearch] = useState(""); const [dateFilter, setDateFilter] = useState(""); const [page, setPage] = useState(1); const rowsPerPage = 10;
  const fetchLeads = () => API.get("/leads").then((res) => setLeads((Array.isArray(res.data) ? res.data : res.data.leads || []).filter((lead) => lead.source === "excel"))).catch(console.error);
  useEffect(() => { fetchLeads(); }, []);
  useEffect(() => setPage(1), [search, dateFilter]);
  const filtered = useMemo(() => leads.filter((lead) => { const query = search.toLowerCase(); return (!query || [lead.name, lead.email, lead.mobile, lead.insuranceType].some((value) => value?.toLowerCase().includes(query))) && (!dateFilter || new Date(lead.createdAt).toDateString() === new Date(dateFilter).toDateString()); }), [leads, search, dateFilter]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / rowsPerPage)); const visible = filtered.slice((page - 1) * rowsPerPage, page * rowsPerPage);
  const download = () => { const rows = [[...headings.slice(0, -1)], ...filtered.map((lead) => [lead.name, lead.email, lead.mobile, lead.insuranceType, lead.message, lead.status, new Date(lead.createdAt).toLocaleString()])]; const blob = new Blob([rows.map((row) => row.map(csvValue).join(",")).join("\n")], { type: "text/csv;charset=utf-8;" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `insure365-excel-leads${dateFilter ? `-${dateFilter}` : "-all"}.csv`; anchor.click(); URL.revokeObjectURL(url); };
  const deleteLead = async (id) => { if (!window.confirm("Delete this lead?")) return; try { await API.delete(`/leads/${id}`); setLeads((items) => items.filter((lead) => lead._id !== id)); } catch { alert("Could not delete this lead."); } };
  const deleteAllLeads = async () => { if (!leads.length || !window.confirm("Delete all Excel-uploaded leads? This cannot be undone.")) return; try { await API.delete("/leads/delete-all", { data: { type: "excel" } }); setLeads([]); setPage(1); } catch { alert("Could not delete Excel leads."); } };
  const cell = { color: "#e2e8f0", whiteSpace: "nowrap" };
  return <ProtectedRoute><Navbar /><Box sx={{ minHeight: "calc(100vh - 64px)", background: "#020617", p: { xs: 2, md: 3 } }}><Box sx={{ maxWidth: 1500, mx: "auto" }}><Box sx={{ mb: 3 }}><Typography variant="h4" sx={{ color: "#f8fafc", fontWeight: 800 }}>New Leads</Typography><Typography sx={{ color: "#94a3b8", mt: .5 }}>Excel-uploaded leads. Use the date filter before downloading, or download every lead.</Typography></Box><Box sx={{ display: "flex", flexWrap: "wrap", gap: 1.5, mb: 2.5 }}><TextField placeholder="Search name, email or mobile" value={search} onChange={(event) => setSearch(event.target.value)} size="small" sx={{ minWidth: { xs: "100%", sm: 280 }, ...inputSx }} /><TextField type="date" value={dateFilter} onChange={(event) => setDateFilter(event.target.value)} size="small" sx={{ ...inputSx }} /><Button variant="contained" startIcon={<DownloadIcon />} onClick={download} sx={{ textTransform: "none", fontWeight: 700 }}>Download {dateFilter ? "filtered" : "all"} leads</Button><Button color="error" variant="contained" startIcon={<DeleteIcon />} onClick={deleteAllLeads} sx={{ textTransform: "none", fontWeight: 700 }}>Delete all leads</Button></Box><Box sx={tableSx}><Table size="small"><TableHead><TableRow>{headings.map((heading) => <TableCell key={heading} sx={{ ...cell, fontWeight: 800, color: "#93c5fd" }}>{heading}</TableCell>)}</TableRow></TableHead><TableBody>{visible.map((lead) => <TableRow key={lead._id} hover><TableCell sx={cell}>{lead.name || "-"}</TableCell><TableCell sx={cell}>{lead.email || "-"}</TableCell><TableCell sx={cell}>{lead.mobile || "-"}</TableCell><TableCell sx={cell}>{lead.insuranceType || "-"}</TableCell><TableCell sx={{ ...cell, maxWidth: 220, overflow: "hidden", textOverflow: "ellipsis" }}>{lead.message || "-"}</TableCell><TableCell sx={cell}>{lead.status || "new"}</TableCell><TableCell sx={cell}>{new Date(lead.createdAt).toLocaleString()}</TableCell><TableCell sx={cell}><Button color="error" size="small" startIcon={<DeleteIcon />} onClick={() => deleteLead(lead._id)} sx={{ textTransform: "none" }}>Delete</Button></TableCell></TableRow>)}</TableBody></Table></Box><Pager shown={visible.length} total={filtered.length} page={page} count={pageCount} setPage={setPage} /></Box></Box></ProtectedRoute>;
}
const inputSx = { input: { color: "#f8fafc" }, label: { color: "#94a3b8" }, "& .MuiOutlinedInput-root": { background: "#0f172a", "& fieldset": { borderColor: "#334155" }, "&:hover fieldset": { borderColor: "#64748b" } } }; const tableSx = { overflowX: "auto", background: "#0f172a", border: "1px solid #1e293b", borderRadius: 2, "& .MuiTableRow-root:hover": { background: "rgba(30,41,59,.7)" } }; function Pager({ shown, total, page, count, setPage }) { return <Box sx={{ mt: 2.5, display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 1 }}><Typography sx={{ color: "#94a3b8" }}>Showing {shown} of {total} leads</Typography><Pagination count={count} page={page} onChange={(_, value) => setPage(value)} sx={{ "& .MuiPaginationItem-root": { color: "#e2e8f0" }, "& .Mui-selected": { background: "#2563eb !important" } }} /></Box>; }
