"use client";
import { useEffect, useMemo, useState } from "react";
import ProtectedRoute from "@/components/ProtectedRoute";
import Navbar from "@/components/Navbar";
import API from "@/lib/api";
import DownloadIcon from "@mui/icons-material/Download";
import { Box, Button, MenuItem, Pagination, Select, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";

const headings = ["Name", "DOB", "Mobile", "Alternative Mobile", "Email", "Insurance", "Brand", "Term & PPT", "Application No.", "Nominee", "Nominee DOB", "Short Address", "Submitted", "Status"];
const csvValue = (value) => `"${String(value ?? "").replaceAll('"', '""')}"`;

export default function Dashboard() {
  const [contacts, setContacts] = useState([]); const [search, setSearch] = useState(""); const [dateFilter, setDateFilter] = useState(""); const [page, setPage] = useState(1); const rowsPerPage = 10;
  const fetchContacts = () => API.get("/contact").then((res) => setContacts(Array.isArray(res.data) ? res.data : [])).catch(console.error);
  useEffect(() => { fetchContacts(); }, []); useEffect(() => setPage(1), [search, dateFilter]);
  const filtered = useMemo(() => contacts.filter((contact) => { const query = search.toLowerCase(); return (!query || [contact.name, contact.mobile, contact.alternativeMobile, contact.email, contact.applicationNumber, contact.brandType, contact.nomineeName].some((value) => value?.toLowerCase().includes(query))) && (!dateFilter || new Date(contact.createdAt).toDateString() === new Date(dateFilter).toDateString()); }), [contacts, search, dateFilter]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / rowsPerPage)); const visible = filtered.slice((page - 1) * rowsPerPage, page * rowsPerPage);
  const updateStatus = async (id, status) => { try { await API.put(`/leads/${id}`, { status }); setContacts((items) => items.map((contact) => contact._id === id ? { ...contact, status } : contact)); } catch { fetchContacts(); } };
  const download = () => { const rows = [[...headings], ...filtered.map((contact) => [contact.name, contact.dob, contact.mobile, contact.alternativeMobile, contact.email, contact.insuranceType, contact.brandType, contact.termAndPpt, contact.applicationNumber, contact.nomineeName, contact.nomineeDob, contact.shortAddress, new Date(contact.createdAt).toLocaleString(), contact.status || "new"])]; const blob = new Blob([rows.map((row) => row.map(csvValue).join(",")).join("\n")], { type: "text/csv;charset=utf-8;" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `insure365-contact-forms${dateFilter ? `-${dateFilter}` : "-all"}.csv`; link.click(); URL.revokeObjectURL(url); };
  const cell = { color: "#e2e8f0", whiteSpace: "nowrap" }; const input = { input: { color: "#f8fafc" }, "& .MuiOutlinedInput-root": { background: "#0f172a", "& fieldset": { borderColor: "#334155" } } };
  return <ProtectedRoute><Navbar /><Box sx={{ minHeight: "calc(100vh - 64px)", background: "#020617", p: { xs: 2, md: 3 } }}><Box sx={{ maxWidth: 1500, mx: "auto" }}><Typography variant="h4" sx={{ color: "#f8fafc", fontWeight: 800 }}>Contact form dashboard</Typography><Typography sx={{ color: "#94a3b8", mt: .5, mb: 3 }}>All application details submitted from the website and popup form.</Typography><Box sx={{ display: "flex", flexWrap: "wrap", gap: 1.5, mb: 2.5 }}><TextField placeholder="Search contact data" value={search} onChange={(event) => setSearch(event.target.value)} size="small" sx={{ minWidth: { xs: "100%", sm: 280 }, ...input }} /><TextField type="date" value={dateFilter} onChange={(event) => setDateFilter(event.target.value)} size="small" sx={input} /><Button variant="contained" startIcon={<DownloadIcon />} onClick={download} sx={{ textTransform: "none", fontWeight: 700 }}>Download {dateFilter ? "filtered" : "all"} contacts</Button></Box><Box sx={{ overflowX: "auto", background: "#0f172a", border: "1px solid #1e293b", borderRadius: 2, "& .MuiTableRow-root:hover": { background: "rgba(30,41,59,.7)" } }}><Table size="small"><TableHead><TableRow>{headings.map((heading) => <TableCell key={heading} sx={{ ...cell, color: "#93c5fd", fontWeight: 800 }}>{heading}</TableCell>)}</TableRow></TableHead><TableBody>{visible.map((contact) => <TableRow key={contact._id}>{[contact.name, contact.dob, contact.mobile, contact.alternativeMobile, contact.email, contact.insuranceType, contact.brandType, contact.termAndPpt, contact.applicationNumber, contact.nomineeName, contact.nomineeDob].map((value, index) => <TableCell key={headings[index]} sx={cell}>{value || "-"}</TableCell>)}<TableCell sx={{ ...cell, maxWidth: 220, overflow: "hidden", textOverflow: "ellipsis" }}>{contact.shortAddress || "-"}</TableCell><TableCell sx={cell}>{new Date(contact.createdAt).toLocaleString()}</TableCell><TableCell><Select value={contact.status || "new"} onChange={(event) => updateStatus(contact._id, event.target.value)} size="small" sx={{ color: "#e2e8f0", minWidth: 140, ".MuiOutlinedInput-notchedOutline": { borderColor: "#475569" }, ".MuiSvgIcon-root": { color: "#e2e8f0" } }}>{[["new", "New"], ["interested", "Interested"], ["not_interested", "Not interested"], ["follow_up", "Follow up"]].map(([value, label]) => <MenuItem key={value} value={value}>{label}</MenuItem>)}</Select></TableCell></TableRow>)}</TableBody></Table></Box><Box sx={{ mt: 2.5, display: "flex", justifyContent: "space-between", flexWrap: "wrap", alignItems: "center", gap: 1 }}><Typography sx={{ color: "#94a3b8" }}>Showing {visible.length} of {filtered.length} contacts</Typography><Pagination count={totalPages} page={page} onChange={(_, value) => setPage(value)} sx={{ "& .MuiPaginationItem-root": { color: "#e2e8f0" }, "& .Mui-selected": { background: "#2563eb !important" } }} /></Box></Box></Box></ProtectedRoute>;
}
